routes/web.php
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [ShopController::class, 'showIndex'])->name('home');
Route::get('product/{id}',[ProductsController::class, 'show'])->name('product');
Route::get('product/{id}/statistiky',[ProductsController::class, 'showStats'])->name('product.stats')->middleware('can:manage-objednavky');


Route::prefix('obchod')->group(function() {
    Route::get('/muzi', [ShopController::class, 'showIndex'])->name('muzi.index');
    Route::get('/zeny', [ShopController::class, 'showIndex'])->name('zeny.index');
    
    Route::get('/muzi/{name}', [ShopController::class, 'showKategorie'])->name('muzi.kategorie');
    Route::get('/zeny/{name}', [ShopController::class, 'showKategorie'])->name('zeny.kategorie');;
    Route::get('/{name}', [ShopController::class, 'showKategorie'])->name('obchod.kategorie');;
    
    Route::get('/muzi/{name}/{podkategorie}', [ShopController::class, 'showPodkategorie'])->name('muzi.podkategorie');
    Route::get('/zeny/{name}/{podkategorie}', [ShopController::class, 'showPodkategorie'])->name('zeny.podkategorie');;
    Route::get('/{name}/{podkategorie}', [ShopController::class, 'showPodkategorie'])->name('obchod.podkategorie');;
});

Auth::routes();

//KOSIK

Route::prefix('kosik')->name('kosik.')->group(function () {
    Route::get('/', [KosikController::class, 'show'])->name('show');
    Route::get('/checkout', [KosikController::class, 'checkout'])->name('checkout');
    Route::post('/payment', [KosikController::class, 'payment'])->name('payment');
    Route::get('/payment', [KosikController::class, 'paymentGET'])->name('paymentGET');
    Route::post('/finishPayment', [KosikController::class, 'finishPayment'])->name('finishpayment');
    Route::view('/success', 'obchod.kosik.success');
});

//MODERATOR
Route::group(['middleware' => 'auth'], function() {
    Route::get('admin/objednavky', [Admin\ObjednavkyController::class, 'show'])->name('admin.objednavky')->middleware('can:manage-objednavky');

//ADMIN
    Route::group(['middleware' => 'can:manage-shop'], function() {
       
        Route::prefix('obchod')->group(function () {
            Route::post('/pridatProdukt', [ProductsController::class, 'save'])->name('product.pridat');
            Route::put('/product/editProdukt',[ProductsController::class, 'update'])->name('product.update');
        
            Route::post('/pridatKategorie', [KategorieController::class, 'save'])->name('kategorie.pridat');
            Route::post('/odebratKategorie', [KategorieController::class, 'delete'])->name('kategorie.odebrat');
        
            Route::post('/odebratPodkategorie', [PodkategorieController::class, 'delete'])->name('podkategorie.odebrat');
            Route::post('/pridatPodkategorie', [PodkategorieController::class, 'save'])->name('podkategorie.pridat');
        
            Route::post('/pridatSize', [SizesController::class, 'store'])->name('size.pridat');
            Route::post('/odebratSize', [SizesController::class, 'destroy'])->name('size.odebrat');
        
            Route::post('/pridatZnacka', [ZnackyController::class, 'store'])->name('znacka.pridat');
            Route::post('/odebratZnacka', [ZnackyController::class, 'destroy'])->name('znacka.odebrat');
        });
    });
});

//PERMISSIONS
Route::prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function() {
    Route::resource('/users', Admin\UsersController::class, ['except' => ['show', 'create', 'store']]);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function products() {
        return $this->belongsToMany(Product::class);
    }

    public function hasAnyRoles($roles)
    {
        if ($this->roles()->whereIn('name', $roles)->first()) {
            return true;
        } else {
            return false;
        }
    }
    
    public function hasRole($role)
    {
        if ($this->roles()->where('name', $role)->first()) {
            return true;
        } else {
            return false;
        }
    }
    
    public function purchasedProduct($product) {
        if($this->products->where('id', $product)->first()) {
            return true;
        } else {
            return false;
        }
    }

    public function hasRating($product) {
        if($this->rating()->wherePivot('product_id', $product->id)->first()) {
            return false;
        } else {
            return true;
        }
    }

    public function product() {
        return $this->BelongsToMany(Product::class, 'product_rating_user')->withPivot('rating_id');
    }

    public function rating() {
        return $this->BelongsToMany(Rating::class, 'product_rating_user')->withPivot('product_id');
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Role;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::all();
        
        return view('admin.users.index', [
            'users' => $users
        ]);
    }

    public function edit(User $user)
    {
        $roles = Role::all();

        return view('admin.users.edit', [
            'user' => $user,
            'roles' => $roles
        ]);
    }

    public function update(Request $request, User $user)
    {
        $user->roles()->sync($request->roles);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->save();

        return redirect()->route('admin.users.index');
    }
    
    public function destroy(User $user)
    {
        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

app/Http/Livewire/Admin/Users.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use App\Models\User;

class Users extends Component
{
    public $searchInput;
    public $users;

    public function mount() {
        $roleName = 'user';
        $this->users = User::whereHas('roles', function ($query) use ($roleName) {
            $query->where('name', '!=', $roleName);
        })->get();
    }

    public function render()
    {
        return view('livewire.admin.users');
    }

    public function search() {
        $this->users = User::where('email', 'like', "%$this->searchInput%")->get();
    }
}

resources/views/Admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
        <div class="container">
            <div class="center-screen">
                <div class="col-md-8">
                    <div class="card logincard">
                        <div class="card-header">{{ __('Edit User') }} {{ $user->name }} </div>

                        <div class="card-body">
                            <form action="{{ route('admin.users.update', $user) }}" method="POST">
                                <div class="form-group row">
                                    <label for="email"
                                        class="col-md-2 col-form-label text-md-right text-white">E-mail</label>

                                    <div class="col-md-6">
                                        <input id="email" type="email"
                                            class="form-control @error('email') is-invalid @enderror" name="email"
                                            value="{{ $user->email }}" required autocomplete="email" autofocus>

                                        @error('email')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="name" class="col-md-2 col-form-label text-md-right text-white">Jméno</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text"
                                            class="form-control @error('name') is-invalid @enderror" name="name"
                                            value="{{ $user->name }}" required autofocus>

                                        @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>

                                @csrf
                                {{ method_field('PUT') }}
                                <div class="form-group row">
                                    <label for="Roles" class="col-md-2 col-form-label text-md-right text-white">Role</label>

                                    <div class="col-md-6">
                                        @foreach ($roles as $role)
                                            <div class="form-check text-white text-left">
                                                <input type="checkbox" name="roles[]" value="{{ $role->id }}" @if ($user->roles->pluck('id')->contains($role->id)) checked @endif>
                                                <label>{{ $role->name }}</label>
                                            </div>
                                        @endforeach
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary mx-2">Aktualizovat</button>
                                <a href="{{ route('admin.users.index') }}"><button type="submit"
                                        class="btn btn-secondary mx-2">Zpět</button></a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/Admin/users/index.blade.php
@extends('layouts.app')

@section('content')
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @livewire('admin.users')
                </div>
            </div>
        </div>
@endsection