routes/web.php
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [ShopController::class, 'showIndex'])->name('home');
Route::get('product/{id}',[ProductsController::class, 'show'])->name('product');
Route::get('product/{id}/statistiky',[ProductsController::class, 'showStats'])->name('product.stats')->middleware('can:manage-objednavky');


Route::prefix('obchod')->group(function() {
    Route::get('/muzi', [ShopController::class, 'showIndex'])->name('muzi.index');
    Route::get('/zeny', [ShopController::class, 'showIndex'])->name('zeny.index');
    
    Route::get('/muzi/{name}', [ShopController::class, 'showKategorie'])->name('muzi.kategorie');
    Route::get('/zeny/{name}', [ShopController::class, 'showKategorie'])->name('zeny.kategorie');;
    Route::get('/{name}', [ShopController::class, 'showKategorie'])->name('obchod.kategorie');;
    
    Route::get('/muzi/{name}/{podkategorie}', [ShopController::class, 'showPodkategorie'])->name('muzi.podkategorie');
    Route::get('/zeny/{name}/{podkategorie}', [ShopController::class, 'showPodkategorie'])->name('zeny.podkategorie');;
    Route::get('/{name}/{podkategorie}', [ShopController::class, 'showPodkategorie'])->name('obchod.podkategorie');;
});

Auth::routes();

//KOSIK

Route::prefix('kosik')->name('kosik.')->group(function () {
    Route::get('/', [KosikController::class, 'show'])->name('show');
    Route::get('/checkout', [KosikController::class, 'checkout'])->name('checkout');
    Route::post('/payment', [KosikController::class, 'payment'])->name('payment');
    Route::get('/payment', [KosikController::class, 'paymentGET'])->name('paymentGET');
    Route::post('/finishPayment', [KosikController::class, 'finishPayment'])->name('finishpayment');
    Route::view('/success', 'obchod.kosik.success');
});

//MODERATOR
Route::group(['middleware' => 'auth'], function() {
    Route::get('admin/objednavky', [Admin\ObjednavkyController::class, 'show'])->name('admin.objednavky')->middleware('can:manage-objednavky');

//ADMIN
    Route::group(['middleware' => 'can:manage-shop'], function() {
       
        Route::prefix('obchod')->group(function () {
            Route::post('/pridatProdukt', [ProductsController::class, 'save'])->name('product.pridat');
            Route::put('/product/editProdukt',[ProductsController::class, 'update'])->name('product.update');
        
            Route::post('/pridatKategorie', [KategorieController::class, 'save'])->name('kategorie.pridat');
            Route::post('/odebratKategorie', [KategorieController::class, 'delete'])->name('kategorie.odebrat');
        
            Route::post('/odebratPodkategorie', [PodkategorieController::class, 'delete'])->name('podkategorie.odebrat');
            Route::post('/pridatPodkategorie', [PodkategorieController::class, 'save'])->name('podkategorie.pridat');
        
            Route::post('/pridatSize', [SizesController::class, 'store'])->name('size.pridat');
            Route::post('/odebratSize', [SizesController::class, 'destroy'])->name('size.odebrat');
        
            Route::post('/pridatZnacka', [ZnackyController::class, 'store'])->name('znacka.pridat');
            Route::post('/odebratZnacka', [ZnackyController::class, 'destroy'])->name('znacka.odebrat');
        });
    });
});

//PERMISSIONS
Route::prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function() {
    Route::resource('/users', Admin\UsersController::class, ['except' => ['show', 'create', 'store']]);
});

app/Http/Controllers/KosikController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\checkoutRequest;
use App\Models\Size;
use App\Models\Objednavka;
use Illuminate\Support\Facades\Session;
use App\Services\KosikService;
use Illuminate\Support\Facades\Auth;

class KosikController extends Controller
{

    // ukázat košík
    public function show()
    {
        $total = (new KosikService())->kosikTotal();
        $products = (new KosikService())->getProducts();
        $sizes = Size::all();
        $paymentSession = Session::get('payment');
        $paymentSession ?: $paymentSession = 1;
        $kosikContent = Session::get('kosik');

        if ($products) {
            return view('obchod.kosik.kosik', [
                'products' => $products,
                'kosikSession' => $kosikContent,
                'sizes' => $sizes,
                'payment' => $paymentSession,
                'total' => $total
            ]);
        } else {
            return view('obchod.kosik.kosik');
        }
    }

    //ukázat checkout
    public function checkout()
    {
        $total = (new KosikService())->kosikTotal();
        $products = (new KosikService())->getProducts();
        $kosikContent = Session::get('kosik');
        $paymentSession = Session::get('payment');
        $paymentSession ?: $paymentSession = 1;

        if ($products) {
            return view('obchod.kosik.checkout', [
                'checkoutitems' => $kosikContent,
                'prods' => $products,
                'payment' => $paymentSession,
                'total' => $total
            ]);
        } else {
            return view('obchod.kosik.checkout', [
                'checkoutitems' => $kosikContent
            ]);
        }
    }

    public function payment(checkoutRequest $req)
    {
        $req->validated();
        Session::put('payment', $req->except('_token'));
        return $this->paymentGET();
    }

    public function paymentGET()
    {
        $total = (new KosikService())->kosikTotal();
        $products = (new KosikService())->getProducts();
        $paymentSession = Session::get('payment');
        $kosikSession = Session::get('kosik');

        if (isset($paymentSession)) {
            return view('obchod.kosik.payment', [
                'kosikSession' => $kosikSession,
                'paymentSession' => $paymentSession,
                'products' => $products,
                'total' => $total
            ]);
        } else {
            return redirect('/kosik/checkout');
        }
    }

    public function finishPayment()
    {
        $kosikSession = Session::get('kosik');
        $products = (new KosikService())->getProducts();
        $paymentSession = Session::get('payment');

        foreach ($products as $product) {
            $size = $product->sizes()->where('sizes', $kosikSession[$product->id]['size'])->first();
            $vysledek = $size->pivot->stock - $kosikSession[$product->id]['pocet'];
            if ($vysledek < 0) {
                return back()->withErrors('Snažíte se objednat: ' . $product->name . ' ale takový počet nemáme momentálně na skladě.');
            }
        }
        foreach ($products as $product) {
            $size = $product->sizes()->where('sizes', $kosikSession[$product->id]['size'])->first();
            $vysledek = $size->pivot->stock - $kosikSession[$product->id]['pocet'];
            $product->bought += $kosikSession[$product->id]['pocet'];
            $product->sizes()->sync(
                [
                    $size->id => [
                        'stock' => $vysledek
                    ]
                ],
                false
            );
        }

        $objednavka = Objednavka::create([
            'objednavka_id' => sha1(time()),
            'total' => (new KosikService())->kosikTotal(),
            'user_email' => $paymentSession['email'],
            'user_jmeno' => $paymentSession['jmeno'],
            'user_prijmeni' => $paymentSession['prijmeni'],
            'user_mesto' => $paymentSession['mesto'],
            'user_ulice' => $paymentSession['ulice'],
            'user_psc' => $paymentSession['psc'],
            'user_telefon' => $paymentSession['telefon'],
            'preprava' => $paymentSession['preprava'],
            'platba' => $paymentSession['platba'],
        ]);

        foreach ($products as $product) {
            $objednavka->products()->attach([
                $product->id => [
                    'pocet' => $kosikSession[$product->id]['pocet'],
                    'size' => $kosikSession[$product->id]['size'],
                    'created_at' => now(),
                    'updated_at' => now()
                ]
            ]);
        }

        if(Auth::check()) {
            foreach($products as $product) {
                Auth::User()->products()->attach($product);
            }
        }
        Session::forget('kosik');
        return redirect('kosik/success');
    }
}

app/Http/Livewire/Kosik.php
<?php

namespace App\Http\Livewire;

use App\Models\Product;
use Illuminate\Support\Facades\Session;
use Livewire\Component;
use App\Services\KosikService;

class Kosik extends Component
{
    public $pocet = array();
    public $size = array();
    public $checkstock = false;
    
    public function mount()
    {
        $kosikSession = Session::get('kosik');
        $products = (new KosikService())->getProducts();
       
        if ($products != 0) {
            foreach ($products as $product) {
                $this->size[$product->id] = $kosikSession[$product->id]['size'];
                $this->pocet[$product->id] = $kosikSession[$product->id]['pocet'];
            }
        }
    }
    public function render()
    {
        $kosikSession = Session::get('kosik');
        $products = (new KosikService())->getProducts();
        return view('livewire.kosik', [
            'products' => $products,
            'kosikSession' => $kosikSession
        ]);
    }

    public function destroy($id)
    {
        $this->dispatchBrowserEvent('swal:title-alert', [
                'title' => 'Produkt úspěšně odebrán.',
                'type' => 'success'
            ]);
        Session::pull('kosik.' . $id);
        $this->emit('updateKosik');
        $this->emit('updateCount');
    }
    public function sizeChange($id)
    {
        $kosikSession = Session::get('kosik');
        $product = Product::find($id);
        $productStock = $product->sizes->where('sizes', $this->size[$id])->first()->pivot->stock;
    
        if ($productStock < $this->pocet[$id]) {
            $this->pocet[$id] = $productStock;
            $kosikSession = Session::get('kosik');
            $kosikSession[$id]['size'] = $this->size[$id];
            Session::put('kosik', $kosikSession);

            $this->dispatchBrowserEvent('swal:title-alert', [
                'title' => 'Snažíte se objednat více kusů než momentálně máme na skladě.',
                'type' => 'error'
            ]);
            
        } else {
            $kosikSession = Session::get('kosik');
            $kosikSession[$id]['size'] = $this->size[$id];
            Session::put('kosik', $kosikSession);
        }
        $this->pocetChange($id);
    }
    public function pocetChange($id)
    {
        $kosikSession = Session::get('kosik');
        $product = Product::find($id);
        $productStock = $product->sizes->where('sizes', $kosikSession[$product->id]['size'])->first()->pivot->stock;

        if ($productStock < $this->pocet[$id]) {
            $this->pocet[$id] = $productStock;
            $this->dispatchBrowserEvent('swal:title-alert', [
                    'title' => 'Snažíte se objednat více kusů než momentálně máme na skladě.',
                    'type' => 'error'
                ]);
        } else {
            ($this->pocet[$id] < 1) ? $this->pocet[$id] = 1 : '';
            $kosikSession[$id]['pocet'] = $this->pocet[$id];
            Session::put('kosik', $kosikSession);
            
            $this->emit('updateKosik');
        }
    }
}

resources/views/obchod/kosik/checkout.blade.php
@extends('layouts.app')
@include('layouts.kosikmenu')
@section('content')
    <div class="container">
        @if (isset($checkoutitems) && $checkoutitems)
            <div class="row ">
                <div class="col my-5 checkoutcol">
                    <h1 class=" py-2">Adresa</h1>
                    <div class="adress-form ">
                        <form action="{{ route('kosik.payment') }}" method="POST" id="adressform" name="adressform">
                            @csrf

                            <div class=" d-flex">
                                <h5 class="">E-mailová adresa</h5>
                                @error('email') 
                                    <p class=" mx-2 text-danger">{{ $message }}</p> 
                                @enderror
                            </div>
                            <input name="email" type="text" class="mb-2 w-100" value="@if ($payment !=1) {{ $payment['email'] }} @else {{ old('email') }} @endif">

                            <div class="d-flex">
                                <h5 class="">Křestní jméno</h5>
                                @error('jmeno') 
                                    <p class=" mx-2 text-danger">{{ $message }}</p> 
                                @enderror
                            </div>
                            <input name="jmeno" type="text" class="mb-2 w-100" value="@if ($payment !=1) {{ $payment['jmeno'] }} @else {{ old('jmeno') }} @endif">

                            <div class="d-flex">
                                <h5 class="">Příjmení</h5>
                                @error('prijmeni') 
                                    <p class=" mx-2 text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <input name="prijmeni" type="text" class="mb-2 w-100" value="@if ($payment !=1) {{ $payment['prijmeni'] }} @else {{ old('prijmeni') }} @endif">

                            <div class="d-flex">
                                <h5 class="">Město</h5>
                                @error('mesto') 
                                    <p class=" mx-2 text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <input name="mesto" type="text" class="mb-2 w-100" value="@if ($payment !=1) {{ $payment['mesto'] }} @else {{ old('mesto') }} @endif">

                            <div class="d-flex">
                                <h5 class="">Ulice</h5>
                                @error('ulice') 
                                    <p class=" mx-2 text-danger">{{ $message }}</p> 
                                @enderror
                            </div>
                            <input name="ulice" type="text" class="mb-2 w-100" value="@if ($payment !=1) {{ $payment['ulice'] }} @else {{ old('ulice') }} @endif">

                            <div class="d-flex">
                                <h5 class="">PSČ</h5>
                                @error('psc') 
                                    <p class=" mx-2 text-danger">{{ $message }}</p> 
                                @enderror
                            </div>
                            <input name="psc" type="text" class="mb-2 w-100" value="@if ($payment !=1) {{ $payment['psc'] }} @else {{ old('psc') }} @endif">

                            <div class="d-flex">
                                <h5 class="">Telefonní číslo</h5>
                                @error('telefon')
                                    <p class=" mx-2 text-danger">{{ $message }}</p> 
                                @enderror
                            </div>
                            <input name="telefon" type="text" class="mb-2 w-100" value="@if ($payment !=1) {{ $payment['telefon'] }} @else {{ old('telefon') }} @endif">

                            <h1 class=" py-2 ">Způsob dopravy</h1>
                            <div class="preprava-group my-4 d-flex">
                                <div class="preprava-checkbox ">
                                    <input name="preprava" class="checkboxpreprava" type="checkbox" id="ppl" value="ppl"
                                        {{ ($payment != 1 && $payment['preprava'] == 'ppl') ? 'checked' : '' }}
                                        {{ (empty($payment['preprava']) ? 'checked' : '') }}
                                    >
                                    <label for="ppl">PPL (79Kč)</label>
                                </div>

                                <div class="preprava-fotka text-right">
                                    <img src="{{ url('images/ppl.jpg') }}" style="width:10vh;">
                                </div>
                            </div>

                            <div class="preprava-group my-4 d-flex">
                                <div class="preprava-checkbox ">
                                    <input id="ceskaposta" class="checkboxpreprava" name="preprava"  type="checkbox" value="ceskaposta"
                                    {{ ($payment != 1 && $payment['preprava'] == 'ceskaposta') ? 'checked' : '' }}
                                    >
                                    <label for="ceskaposta">Česká pošta (59Kč)</label>
                                </div>

                                <div class="preprava-fotka text-right">
                                    <img src="{{ url('images/ceskaposta.png') }}" style="width:10vh;">
                                </div>
                            </div>

                            <h1 class=" py-2 ">Platební metody</h1>
                            <div class="preprava-group my-4 d-flex">
                                <input id="karta" class="checkboxplatba" name="platba" type="checkbox" value="karta" 
                                {{ ($payment != 1 && $payment['platba'] == 'karta') ? 'checked' : '' }}
                                {{ (empty($payment['platba']) ? 'checked' : '') }}
                                >
                                <label for="karta">Platební karta (Zdarma)</label>
                            </div>

                            <div class="preprava-group my-4 d-flex">
                                <input id="banka" class="checkboxplatba" name="platba" type="checkbox" value="banka" 
                                {{ ($payment != 1 && $payment['platba'] == 'banka') ? 'checked' : '' }}
                                >
                                <label for="banka">Bankovní převod (Zdarma)</label>
                            </div>

                            <div class="preprava-group my-4 d-flex">
                                <input id="dobirka" class="checkboxplatba" name="platba" type="checkbox" value="dobirka"
                                {{ ($payment != 1 && $payment['platba'] == 'dobirka') ? 'checked' : '' }}
                                >
                                <label for="dobirka">Dobírka (19Kč)</label>
                            </div>
                        </form>
                        <div class="buttonlist d-flex mr-auto py-5">
                            <a href="{{ url('kosik') }}">
                                <button class="btn btn-primary ">Zpět</button>
                            </a>
                            <input class="btn btn-success ml-auto" type="submit"  form="adressform" value="Pokračovat">
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 ">
                    <div class="sticky-col ">
                        @livewire('kosik-menu')
                    </div>
                </div>
            </div>
        @else
            <h1>Košík je prázdný</h1>
        @endif
    </div>
@endsection

resources/views/obchod/kosik/kosik.blade.php
@extends('layouts.app')
@include('layouts.kosikmenu')
@include('layouts.sweetalert.TitleAlert')

@section('content')
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1 class="text-center py-5">Košík</h1>
                    @livewire('kosik')
                </div>

                <div class="col-xl-3">
                    @livewire('kosik-menu')
                </div>
            </div>
        </div>
@endsection

resources/views/obchod/kosik/payment.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (isset($products) && $products)
            <h1 class="text-center pt-2">Souhrn</h1>
            @if ($errors->any())
                <h5 class="text-danger text-center">{{ $errors->first() }}</h5>
            @endif
            <hr class="hr">
            <div class="row my-5">
                <div class="col-lg-4 mb-2 osobniudaje">
                    <h1 class="py-2 ">Osobní údaje</h1>
                    
                    <p>E-Mail:<span class="text-primary"> {{ $paymentSession['email'] }}</span></p>
                    <p>Jméno:<span class="text-primary"> {{ $paymentSession['jmeno'] }}</span></p>
                    <p>Příjmení:<span class="text-primary"> {{ $paymentSession['prijmeni'] }}</span></p>
                    <p>Město:<span class="text-primary"> {{ $paymentSession['mesto'] }}</span></p>
                    <p>Ulice:<span class="text-primary"> {{ $paymentSession['ulice'] }}</span></p>
                    <p>PSČ:<span class="text-primary"> {{ $paymentSession['psc'] }}</span></p>
                    <p>Telefonní číslo:<span class="text-primary"> {{ $paymentSession['telefon'] }}</span></p>
                </div>
                <div class="col-lg-4 mb-2">
                    <h1 class="text-center py-2">Platba & Doprava</h1>
                    <p class="text-center">Doprava:<span class="text-primary"> {{ $paymentSession['preprava'] }}</span></p>
                    <p class="text-center">Platba:<span class="text-primary"> {{ $paymentSession['platba'] }}</span></p>
                </div>
                <div class="col-lg-4 mb-2 ">
                    <h1 class="text-center py-2">Košík</h1>
                    <div class="row text-center" style="height:2vh;">
                        <div class="payment-product-jmeno"><p>Jméno</p></div>
                        <div class="payment-product-size"><p>Velikost</p></div>
                        <div class="payment-product-pocet"> <p>Počet</p></div>
                        <div class="payment-product-cena d-flex"><p>Cena</p></div>
                    </div>
                    <hr class="hr my-2">
                    @foreach ($products as $product)
                        <div class="row text-center">
                            <div class="payment-product-jmeno">
                                <p class="px-2">{{ $product->name }}</p>
                            </div>

                            <div class="payment-product-size">
                                <p class="px-2">{{ $kosikSession[$product->id]['size'] }}</p>
                            </div>

                            <div class="payment-product-pocet">
                                <p class="px-2">{{ $kosikSession[$product->id]['pocet'] }}</p>
                            </div>

                            <div class="payment-product-cena d-flex">
                                @if($product->sleva == 0)
                                    <p>{{ $product->cena }} Kč</p>
                                @else
                                    <del><p>{{ $product->cena }} Kč</p></del>
                                    <p class="text-danger  px-2">{{ $product->sleva }} Kč </p>
                                @endif
                            </div>
                        </div>
                    @endforeach
                    <div class="row text-center">
                        <div class="payment-product-jmeno">
                            <p class="px-2">Doprava</p>
                        </div>
                        <div class="payment-product-cena d-flex ml-auto">
                            @if($paymentSession['preprava'] == "ppl") 
                                <p class="px-2">79 Kč</p>
                            @else
                                <p class="px-2">59 Kč</p>
                            @endif
                        </div>
                    </div>
                    <div class="row text-center">
                        <div class="payment-product-jmeno">
                            <p class="px-2">Platba</p>
                        </div>
                        <div class="payment-product-cena d-flex ml-auto">
                            @if($paymentSession['platba'] == "karta" || $paymentSession['platba'] == "banka") 
                                <p class="px-2">Zdarma</p>
                            @else
                                <p class="px-2">19 Kč</p>
                            @endif
                        </div>
                    </div>
                    <hr class="hr my-2">
                    <h3 class="text-primary text-center ">{{ $total }} Kč</h3>
                </div>
            </div>
            <hr class="hr my-2">
            <form action="{{ route('kosik.finishpayment') }}" method="post">
                @csrf
                <div class="row justify-content-center py-2">
                    <button type="submit" class="btn btn-success">Dokončit objednávku</button>
                </div>
            </form>
        @else
            <h1>Košík je prázdný</h1>
        @endif
    </div>
@endsection

resources/views/obchod/kosik/success.blade.php
@extends('layouts.app')

@section('content')
        <div class="container text-center">
            <h1 class="text-center mt-3">Objednávka byla úspěšně odeslána.</h1>
            <h2 class="text-center">Na E-mail jsme vám zaslali více informací.</h2>
            <a href="/">
                <button class="btn btn-success my-2">Zpět do obchodu</button>
            </a>
        </div>
@endsection