routes/web.php
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [ShopController::class, 'showIndex'])->name('home');
Route::get('product/{id}',[ProductsController::class, 'show'])->name('product');
Route::get('product/{id}/statistiky',[ProductsController::class, 'showStats'])->name('product.stats')->middleware('can:manage-objednavky');


Route::prefix('obchod')->group(function() {
    Route::get('/muzi', [ShopController::class, 'showIndex'])->name('muzi.index');
    Route::get('/zeny', [ShopController::class, 'showIndex'])->name('zeny.index');
    
    Route::get('/muzi/{name}', [ShopController::class, 'showKategorie'])->name('muzi.kategorie');
    Route::get('/zeny/{name}', [ShopController::class, 'showKategorie'])->name('zeny.kategorie');;
    Route::get('/{name}', [ShopController::class, 'showKategorie'])->name('obchod.kategorie');;
    
    Route::get('/muzi/{name}/{podkategorie}', [ShopController::class, 'showPodkategorie'])->name('muzi.podkategorie');
    Route::get('/zeny/{name}/{podkategorie}', [ShopController::class, 'showPodkategorie'])->name('zeny.podkategorie');;
    Route::get('/{name}/{podkategorie}', [ShopController::class, 'showPodkategorie'])->name('obchod.podkategorie');;
});

Auth::routes();

//KOSIK

Route::prefix('kosik')->name('kosik.')->group(function () {
    Route::get('/', [KosikController::class, 'show'])->name('show');
    Route::get('/checkout', [KosikController::class, 'checkout'])->name('checkout');
    Route::post('/payment', [KosikController::class, 'payment'])->name('payment');
    Route::get('/payment', [KosikController::class, 'paymentGET'])->name('paymentGET');
    Route::post('/finishPayment', [KosikController::class, 'finishPayment'])->name('finishpayment');
    Route::view('/success', 'obchod.kosik.success');
});

//MODERATOR
Route::group(['middleware' => 'auth'], function() {
    Route::get('admin/objednavky', [Admin\ObjednavkyController::class, 'show'])->name('admin.objednavky')->middleware('can:manage-objednavky');

//ADMIN
    Route::group(['middleware' => 'can:manage-shop'], function() {
       
        Route::prefix('obchod')->group(function () {
            Route::post('/pridatProdukt', [ProductsController::class, 'save'])->name('product.pridat');
            Route::put('/product/editProdukt',[ProductsController::class, 'update'])->name('product.update');
        
            Route::post('/pridatKategorie', [KategorieController::class, 'save'])->name('kategorie.pridat');
            Route::post('/odebratKategorie', [KategorieController::class, 'delete'])->name('kategorie.odebrat');
        
            Route::post('/odebratPodkategorie', [PodkategorieController::class, 'delete'])->name('podkategorie.odebrat');
            Route::post('/pridatPodkategorie', [PodkategorieController::class, 'save'])->name('podkategorie.pridat');
        
            Route::post('/pridatSize', [SizesController::class, 'store'])->name('size.pridat');
            Route::post('/odebratSize', [SizesController::class, 'destroy'])->name('size.odebrat');
        
            Route::post('/pridatZnacka', [ZnackyController::class, 'store'])->name('znacka.pridat');
            Route::post('/odebratZnacka', [ZnackyController::class, 'destroy'])->name('znacka.odebrat');
        });
    });
});

//PERMISSIONS
Route::prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function() {
    Route::resource('/users', Admin\UsersController::class, ['except' => ['show', 'create', 'store']]);
});

resources/views/layouts/admin.blade.php
@section('adminmenu')
<div class="admin-menu my-2 ">
    <h3 class="text-center py-2">Admin Menu</h3>
    <hr>
    <ul>
        <li class=" text-center text-white py-2 position-relative d-flex mx-2 justify-content-center">
            <h4 class="py-2">Produkt</h4>
            <button data-toggle="modal" data-target="#adminAddProduct" class="btn btn-outline-success admin-menu-btn">
                <i class="fas fa-plus"></i>
            </button>     
        </li>

        <li class="text-center text-white py-2 position-relative d-flex mx-2 justify-content-center">
            <h4 class="py-2">Velikost</h4>
            <button data-toggle="modal" data-target="#adminAddSize" class="btn btn-outline-success admin-menu-btn">
                <i class="fas fa-plus"></i>
            </button>
        </li>

        <li class="text-center text-white py-2 position-relative d-flex mx-2 justify-content-center">
            <h4 class="py-2">Značka</h4>
            <button data-toggle="modal" data-target="#adminAddZnacka" class="btn btn-outline-success admin-menu-btn">
                <i class="fas fa-plus"></i>
            </button>    
        </li>
    </ul>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
        integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
        crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-bs4.min.css"
        integrity="sha512-pDpLmYKym2pnF0DNYDKxRnOk1wkM9fISpSOjt8kWFKQeDmBTjSnBZhTd41tXwh8+bRMoSaFsRnznZUiH9i3pxA=="
        crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
        integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
        crossorigin="anonymous" />
    @livewireStyles()
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light shadow-sm {{ request()->is('login') || request()->is('register') ? 'fixed' : '' }}">
            <div class="container">
                <a class="navbar-brand font-medium " href="{{ url('/') }}">
                    {{ config('app.name') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item">
                            <a class="nav-link font-big  muzi mx-3 {{ request()->is('obchod/muzi') || request()->is('obchod/muzi/*') ? 'activemuzi' : '' }} "
                                href="{{ url('/obchod/muzi') }}">Muži</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-big  zeny mx-3  {{ request()->is('obchod/zeny') || request()->is('obchod/zeny/*') ? 'activezeny' : '' }}"
                                href="{{ url('/obchod/zeny') }}">Ženy</a>
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link font-small " href="{{ route('login') }}">Přihlásit se</a>
                                </li>
                            @endif
 
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle font-small" href="#" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                                       Odhlásit se
                                    </a>
                                    @can('manage-users')
                                        <a class="dropdown-item" href="{{ route('admin.users.index') }}">
                                            Úprava uživatelů
                                        </a>
                                        <a class="dropdown-item" href="{{ route('admin.objednavky') }}">
                                            Objednávky
                                        </a>
                                    @endcan
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                        <li class="nav-item kosiknav">
                            <a class="nav-link font-small kosik " href="{{ url('kosik') }}">
                                <span class="px-3 py-1 rounded-pill text-white bg-success kosikcount font-little">
                                    @livewire('kosik-count')
                                </span>
                                <i class="fas fa-shopping-basket font-big text-dark" ></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <main class="main">
            @yield('content')
        </main>

    </div>
    <footer id="footer" class="bg-dark text-white py-5">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="text-center text-white">
                        <h4>FashionShop</h4>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <div class="copyright text-center bg-dark text-white py-2">
        <p>&copy;Copyright 2021 </p>
    </div>

</body>
@livewireScripts()
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js" integrity="sha512-/DXTXr6nQodMUiq+IUJYCt2PPOUjrHJ9wFrqpJ3XkgPNOZVfMok7cRw6CSxyCQxXn6ozlESsSh1/sMCTF1rL/g==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js" integrity="sha512-UwcC/iaz5ziHX7V6LjSKaXgCuRRqbTp1QHpbOJ4l1nw2/boCfZ2KlFIqBUA/uRVF0onbREnY9do8rM/uT/ilqw==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" defer></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/alpinejs/2.3.0/alpine.js" integrity="sha512-nIwdJlD5/vHj23CbO2iHCXtsqzdTTx3e3uAmpTm4x2Y8xCIFyWu4cSIV8GaGe2UNVq86/1h9EgUZy7tn243qdA==" crossorigin="anonymous"></script>
<script src="{{ asset('js/app.js') }}"></script>

@if (Request::is('/') || Request::is('obchod/*') || Request::is('obchod/muzi') || Request::is('obchod/muzi/*') || Request::is('obchod/zeny') || Request::is('obchod/zeny/*'))
    <script src="{{ asset('js/obchod.js') }}" defer></script>
@endif

@if(Request::is('product/*/statistiky'))
    <script src="{{ $graph->cdn() }}" type="application/javascript"></script>
    {{ $graph->script() }}
    {{ ($stockChart) ? $stockChart->script() : '' }}
@endif

<script>
    window.addEventListener('swal:title-alert', event => {
        Swal.fire({
            title: event.detail.title,
            icon: event.detail.type,
            template: '#title-alert'
        })
    })
</script>

</html>

resources/views/layouts/kosikmenu.blade.php
@section('kosikmenu')

<div class="kosikmenu">
    <h2 class="text-center text-white py-2 ">Celková cena</h2>
    <hr class="hr">
    @isset($products)
        @foreach ($products as $i => $prod)
            <div class="d-flex ">
                @if ($prod->sleva == 0)
                    <p class="  text-white mr-auto mx-2 my-1">{{ $prod->name }} </p>
                    <span class="text-white  ml-auto mx-2 my-1"> 
                        {{ $kosikSession[$prod->id]['pocet'] }} x {{ $prod->cena }} Kč
                    </span>
                @else
                    <p class=" text-white  mr-auto mx-2 my-1">{{ $prod->name }} </p>
                    <span class="text-white ml-auto mx-2 my-1">
                        {{ $kosikSession[$prod->id]['pocet'] }} x {{ $prod->sleva }} Kč
                    </span>
                @endif
            </div>
        @endforeach

        @if ($payment != 1)
            <div class="d-flex ">
                <p class=" text-white mr-auto mx-2 my-1">Doprava </p>
                <p class=" text-white ml-auto mx-2 my-1">
                    @if($payment['preprava'] == "ppl")
                        79 Kč
                    @else
                        59 Kč
                    @endif
                </p>
            </div>
            <div class="d-flex ">
                <p class=" text-white mr-auto mx-2 my-1">Platba</p>
                <p class=" text-white ml-auto mx-2 my-1">
                    @if ($payment['platba'] == 'karta' || $payment['platba'] == 'banka')
                        Zdarma 
                    @else
                        19 Kč
                    @endif
                </p>
            </div>
        @endif

        <hr class="hr">
        <h2 class="text-center text-white pb-2">{{ $total }} Kč</h2>

        @if (Request::is('kosik'))
            <div class="tlacitko text-center py-2">
                <a href="{{ route('kosik.checkout') }}">
                    <button type="submit" class="btn btn-outline-success">
                        Přejít do pokladny
                    </button>
                </a>
            </div>
        @endif
    @endisset
</div>

@endsection

resources/views/layouts/productMenu.blade.php
@section('productmenu')
    <div class="obchod-menu">
        <button id="shopMenuButton" style="background:none;border:none;">
            <i class="fas fa-bars text-white obchod-menu-icon"></i>
        </button>
        <div class="obchod-menu-content">
            <div class="obchod-menu-black">
            <h3 class="text-center py-2 text-white">Obchod
                <span class=" 
                    @if ($urls['gender']=='f' ) 
                        zenymenu 
                    @elseif($urls['gender']=='m' ) 
                        muzimenu 
                    @endif 
                ">
                    @if ($urls['gender']=='f' ) 
                        - Ženy
                    @elseif($urls['gender']=='m' ) 
                        - Muži
                    @endif
                </span>
            </h3 class="text-center">
            <hr class="hr">
            <ul class="">
                <a href="
                    @if ($urls['gender'] == 'f')     
                        {{ url('obchod/zeny') }}
                    @elseif ($urls['gender'] == 'm') 
                        {{ url('obchod/muzi') }}
                    @else                            
                        {{ url('/') }}
                    @endif  
                ">   
                    <li class="text-left py-2 px-3 text-white
                        @if (Request::is('obchod/muzi')  || Request::is('obchod/zeny')  || Request::is('/') ) bg-lightgrey @endif">
                        Vše
                    </li>
                </a>

                @foreach ($lists as $list)
                    <a href=" 
                        @if ($urls['gender'] == 'f' )    
                            {{ url('obchod/zeny/' . $list->name) }}
                        @elseif ($urls['gender'] == 'm') 
                            {{ url('obchod/muzi/' . $list->name) }}
                        @else                            
                            {{ url('/obchod/' . $list->name) }} 
                        @endif
                    ">
                        <li class="text-left d-flex py-2 px-3 position-relative @if (str_contains(url()->current(), $list->name)) bg-lightgrey @endif">
                            <p class="text-white my-auto">{{ $list->display_name }}</p>
                                @can('manage-shop')
                                    <form action="{{ route('kategorie.odebrat') }}" method="POST">
                                        @csrf
                                        <input type="hidden" value="{{ $list->id }}" name="id">
                                        <button type="submit" class="trashbtn my-1">
                                            <i class="fas fa-trash  m-2"></i>
                                        </button>
                                    </form>
                                @endcan
                        </li>
                    </a>
        
                    @if (str_contains(url()->current(), $list->name))
                        @foreach ($list->podkategorie as $podkategorie)
                            <a href="
                                @if ($urls['gender']=='f' )      
                                    {{ url('obchod/zeny/' . $list->name) . '/' . $podkategorie->name }}
                                @elseif ($urls['gender'] == 'm') 
                                    {{ url('obchod/muzi/' . $list->name . '/' . $podkategorie->name) }}
                                @else                            
                                    {{ url('/obchod/' . $list->name) . '/' . $podkategorie->name }} 
                                @endif 
                            ">
                                <li class=" text-left py-2 my-1 px-5 podkategorie text-white 
                                    {{ (str_contains(url()->current(), $podkategorie->name)) ? 'bg-grey' : '' }}
                                ">
                                    - {{ $podkategorie->display_name }}
                                        @can('manage-shop')
                                            <form action="{{ route('podkategorie.odebrat') }}" method="POST">
                                                @csrf
                                                <input type="hidden" value="{{ $podkategorie->id }}" name="id">
                                                <button type="submit" class="trashbtn my-1">
                                                    <i class="fas fa-trash  m-2"></i>
                                                </button>
                                            </form>
                                        @endcan
                                </li>
                            </a>
                        @endforeach
                    @endif
                @endforeach

                @can('manage-shop')
                    <li class="text-center admin py-2">
                        <button data-toggle="modal" data-target="#AdminListAddModal"
                            class="btn btn-outline-success ">
                            <i class="fas fa-plus"></i>
                        </button>
                    </li>
                @endcan

            </ul>
        </div>
            @can('manage-shop')
                @yield('adminmenu')
            @endcan
        </div>
    </div>
@endsection